"""медиа файл вопроса

Revision ID: 30e738dddbe5
Revises: a67ed64b005a
Create Date: 2023-03-07 23:51:11.835502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e738dddbe5'
down_revision = 'a67ed64b005a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('filename', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('content_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'content_type')
    op.drop_column('questions', 'filename')
    # ### end Alembic commands ###
