"""username

Revision ID: 4d1ddf816142
Revises: 30e738dddbe5
Create Date: 2023-03-08 12:29:48.077322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1ddf816142'
down_revision = '30e738dddbe5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'username')
    # ### end Alembic commands ###
