"""имя игрока

Revision ID: a67ed64b005a
Revises: 610789524376
Create Date: 2023-03-06 21:07:47.056674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67ed64b005a'
down_revision = '610789524376'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'name')
    # ### end Alembic commands ###
