"""migration v3

Revision ID: b029c0ffae8f
Revises: 
Create Date: 2023-02-28 22:37:50.227311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b029c0ffae8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('email', name=op.f('pk-admins'))
    )
    op.create_table('delayed_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('origin', sa.Enum('VK', 'TELEGRAM', name='origin'), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'name', name=op.f('pk-delayed_messages'))
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-themes')),
    sa.UniqueConstraint('title', name=op.f('uq-themes-title'))
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk-questions-theme_id-themes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-questions')),
    sa.UniqueConstraint('cost', 'theme_id', name=op.f('uq-questions-cost.theme_id'))
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=50), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk-answers-question_id-questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-answers'))
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('origin', sa.Enum('VK', 'TELEGRAM', name='origin'), nullable=False),
    sa.Column('state', sa.Enum('REGISTRATION', 'SELECTION', 'QUESTION', 'ANSWER', name='gamestate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_question_id'], ['questions.id'], name=op.f('fk-games-current_question_id-questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-games')),
    sa.UniqueConstraint('chat_id', 'origin', name=op.f('uq-games-chat_id.origin'))
    )
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk-media_files-question_id-questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-media_files'))
    )
    op.create_table('game_themes',
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk-game_themes-game_id-games')),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk-game_themes-theme_id-themes')),
    sa.UniqueConstraint('theme_id', 'game_id', name=op.f('uq-game_themes-theme_id.game_id'))
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Enum('VK', 'TELEGRAM', name='origin'), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('in_game', sa.Boolean(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('is_leading', sa.Boolean(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk-players-game_id-games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-players')),
    sa.UniqueConstraint('user_id', 'origin', 'chat_id', name=op.f('uq-players-user_id.origin.chat_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('game_themes')
    op.drop_table('media_files')
    op.drop_table('games')
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('themes')
    op.drop_table('delayed_messages')
    op.drop_table('admins')
    op.execute('DROP TYPE origin')
    op.execute('DROP TYPE gamestate')
    # ### end Alembic commands ###
