"""refactoring migration

Revision ID: c1e78cb37cef
Revises: 
Create Date: 2023-03-02 15:13:11.878132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1e78cb37cef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-admins')),
    sa.UniqueConstraint('email', name=op.f('uq-admins-email'))
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-themes'))
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('answer', sa.String(length=80), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk-questions-theme_id-themes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-questions')),
    sa.UniqueConstraint('theme_id', 'cost', name=op.f('uq-questions-theme_id.cost'))
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Enum('VK', 'TELEGRAM', name='origin'), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('WAITING_FOR_LEADING', 'REGISTRATION', 'QUESTION_SELECTION', 'WAITING_FOR_PRESS', 'WAITING_FOR_ANSWER', 'WAITING_FOR_CHECKING', name='game_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_answering', sa.Boolean(), nullable=False),
    sa.Column('already_answered', sa.Boolean(), nullable=False),
    sa.Column('is_leading', sa.Boolean(), nullable=False),
    sa.Column('selected_question', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('current_question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_question_id'], ['questions.id'], name=op.f('fk-games-current_question_id-questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-games')),
    sa.UniqueConstraint('origin', 'chat_id', name=op.f('uq-games-origin.chat_id'))
    )
    op.create_table('game_themes',
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk-game_themes-game_id-games')),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk-game_themes-theme_id-themes')),
    sa.PrimaryKeyConstraint('theme_id', 'game_id', name=op.f('pk-game_themes'))
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Enum('VK', 'TELEGRAM', name='origin'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_answering', sa.Boolean(), nullable=False),
    sa.Column('already_answered', sa.Boolean(), nullable=False),
    sa.Column('is_leading', sa.Boolean(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk-players-game_id-games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-players')),
    sa.UniqueConstraint('origin', 'user_id', name=op.f('uq-players-origin.user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('game_themes')
    op.drop_table('games')
    op.drop_table('questions')
    op.drop_table('themes')
    op.drop_table('admins')
    op.execute('drop type game_state')
    op.execute('drop type origin')
    # ### end Alembic commands ###
