"""migration v6

Revision ID: d96bf70693d1
Revises: 
Create Date: 2023-03-14 18:50:42.003519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd96bf70693d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-admins')),
    sa.UniqueConstraint('email', name=op.f('uq-admins-email'))
    )
    op.create_table('delayed_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('origin', sa.Enum('VK', 'TELEGRAM', name='origin'), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-delayed_messages'))
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-themes')),
    sa.UniqueConstraint('title', name=op.f('uq-themes-title'))
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.String(length=80), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('content_type', sa.String(length=30), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk-questions-theme_id-themes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-questions')),
    sa.UniqueConstraint('theme_id', 'cost', name=op.f('uq-questions-theme_id.cost'))
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Enum('VK', 'TELEGRAM', name='origin'), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('WAITING_FOR_LEADING', 'REGISTRATION', 'QUESTION_SELECTION', 'WAITING_FOR_PRESS', 'WAITING_FOR_ANSWER', 'WAITING_FOR_CAT_IN_BAG_ANSWER', 'WAITING_FOR_CAT_CATCHER', 'WAITING_FOR_CAT_IN_BAG_CHECKING', 'WAITING_FOR_CHECKING', name='gamestate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('selected_questions', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('cat_taken', sa.Boolean(), nullable=False),
    sa.Column('leading_user_id', sa.BigInteger(), nullable=True),
    sa.Column('current_user_id', sa.BigInteger(), nullable=True),
    sa.Column('answering_user_id', sa.BigInteger(), nullable=True),
    sa.Column('current_question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_question_id'], ['questions.id'], name=op.f('fk-games-current_question_id-questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-games')),
    sa.UniqueConstraint('origin', 'chat_id', name=op.f('uq-games-origin.chat_id'))
    )
    op.create_table('game_themes',
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk-game_themes-game_id-games')),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk-game_themes-theme_id-themes')),
    sa.PrimaryKeyConstraint('theme_id', 'game_id', name=op.f('pk-game_themes'))
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Enum('VK', 'TELEGRAM', name='origin'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('already_answered', sa.Boolean(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk-players-game_id-games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-players')),
    sa.UniqueConstraint('origin', 'user_id', 'chat_id', name=op.f('uq-players-origin.user_id.chat_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('game_themes')
    op.drop_table('games')
    op.drop_table('questions')
    op.drop_table('themes')
    op.drop_table('delayed_messages')
    op.drop_table('admins')
    op.execute('drop type origin')
    op.execute('drop type gamestate')
    # ### end Alembic commands ###
